=== amage/Archimedes/plugins/br.org.archimedes.io.xml/FileXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:archimedes="http://www.archimedes.org.br/xml/FileXMLSchema" targetNamespace="http://www.archimedes.org.br/xml/FileXMLSchema" version="0.2">
	<simpleType name="coordinate">
		<restriction base="double"/>
	</simpleType>

	<element name="point" nillable="false">
		<complexType>
			<attribute name="x" type="archimedes:coordinate" use="required"/>
			<attribute name="y" type="archimedes:coordinate" use="required"/>
			<attribute name="z" type="archimedes:coordinate" use="optional"/>
		</complexType>
	</element>

	<element name="line">
		<complexType>
            <sequence maxOccurs="1" minOccurs="1">
				<element ref="archimedes:point"/>
				<element ref="archimedes:point"/>
            </sequence>
		</complexType>
	</element>

	<element name="infiniteline">
		<complexType>
			<sequence maxOccurs="1" minOccurs="1">
				<element ref="archimedes:point"/>
				<element ref="archimedes:point"/>
			</sequence>
		</complexType>
	</element>

	<element name="drawing">
		<complexType>
            <sequence maxOccurs="1" minOccurs="1">
				<element maxOccurs="1" minOccurs="1" ref="archimedes:zoom"/>
				<element maxOccurs="1" minOccurs="1" ref="archimedes:viewport">
				</element>
				
				<element maxOccurs="unbounded" minOccurs="1" ref="archimedes:container"/>
            </sequence>
		</complexType>
	</element>

	<element name="container">
		<complexType>
            <sequence maxOccurs="1" minOccurs="1">
                <sequence maxOccurs="1" minOccurs="1">
                	<element maxOccurs="2" minOccurs="1" ref="archimedes:color"/>
                </sequence>
                <choice maxOccurs="unbounded" minOccurs="0">
					<element ref="archimedes:text"/>
					<element ref="archimedes:circle"/>
					<element ref="archimedes:polyline"/>
					<element ref="archimedes:semiline"/>
					<element ref="archimedes:infiniteline"/>
					<element ref="archimedes:arc"/>
					<element ref="archimedes:rectangle"/>
					<element ref="archimedes:line"/>
					<element ref="archimedes:ellipse"/>
					<element ref="archimedes:leader"/>
					<element ref="archimedes:dimension"/>
                </choice>
            </sequence>
			<attribute name="name" type="string" use="required"/>
			<attribute name="lineStyle" type="int" use="required"/>
			<attribute name="thickness" type="double" use="required"/>
			<attribute name="visible" type="boolean" use="optional"/>
			<attribute name="locked" type="boolean" use="optional"/>
		</complexType>
	</element>

	<element name="semiline">
		<complexType>
			<sequence>
				<element ref="archimedes:point"/>
				<element ref="archimedes:point"/>
			</sequence>
		</complexType>
	</element>

	<element name="polyline">
		<complexType>
			<sequence maxOccurs="unbounded" minOccurs="2">
				<element ref="archimedes:point"/>
			</sequence>
		</complexType>
	</element>

	<element name="arc">
		<complexType>
			<sequence>
				<element ref="archimedes:point"/>
				<element ref="archimedes:point"/>
				<element ref="archimedes:point"/>
			</sequence>
		</complexType>
	</element>

	<element name="rectangle">
		<complexType>
			<sequence>
				<element ref="archimedes:point"/>
				<element ref="archimedes:point"/>
			</sequence>
		</complexType>
	</element>

	<element name="circle">
		<complexType>
			<sequence>
				<element ref="archimedes:point"/>
				<element maxOccurs="1" minOccurs="1" ref="archimedes:radius"/>
			</sequence>
		</complexType>
	</element>
	
	<element name="ellipse">
		<complexType>
			<sequence>
				<element maxOccurs="3" minOccurs="3" ref="archimedes:point"/>
			</sequence>
		</complexType>
	</element>

	<element name="zoom" type="double"/>

	<element name="viewport">
		<complexType>
			<sequence maxOccurs="1" minOccurs="1">
				<element maxOccurs="1" minOccurs="1" ref="archimedes:point"/>
			</sequence>
		</complexType>
	</element>

	<element name="radius" type="double"/>

	<element name="text">
		<complexType>
			<sequence>
				<element ref="archimedes:point"/>
				<element ref="archimedes:size"/>
				<element ref="archimedes:content"/>
				<element ref="archimedes:vector"/>
			</sequence>
		</complexType>
	</element>
	
	<element name="vector">
		<complexType>
			<sequence maxOccurs="1" minOccurs="1">
				<element ref="archimedes:point"/>
			</sequence>
		</complexType>
	</element> 

	<element name="size" type="double"/>
	<element name="content" type="string"/>

	<element name="color">
		<complexType>
			<sequence>
				<element maxOccurs="3" minOccurs="3" ref="archimedes:unsignedByte"/>
			</sequence>
		</complexType>
	</element>

	<element name="unsignedByte" type="unsignedByte"/>

	<element name="leader">
		<complexType>
			<sequence>
				<element maxOccurs="3" minOccurs="3" ref="archimedes:point"/>
			</sequence>
		</complexType>
	</element>
	
	<element name="dimension">
		<complexType>
			<sequence>
				<element maxOccurs="3" minOccurs="3" ref="archimedes:point"/>
				<element maxOccurs="1" minOccurs="1" ref="archimedes:size"/>
			</sequence>
		</complexType>
	</element>

</schema>

=== amage/Archimedes/plugins/br.org.archimedes.io.xml.tests/ExampleFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<drawing xmlns="http://www.archimedes.org.br/xml/FileXMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.archimedes.org.br/xml/FileXMLSchema FileXMLSchema.xsd ">
	<zoom>0.168</zoom>
	<viewport>
		<point x="1694.344" y="-683.745" />
	</viewport>
	<container name="MeuPrimeiroLayer" lineStyle="1" thickness="1.05">
		<color>
			<unsignedByte>247</unsignedByte>
			<unsignedByte>173</unsignedByte>
			<unsignedByte>40</unsignedByte>
		</color>
		<color>
			<unsignedByte>247</unsignedByte>
			<unsignedByte>173</unsignedByte>
			<unsignedByte>40</unsignedByte>
		</color>
		<circle>
			<point x="-191" y="155" />
			<radius>93.193</radius>
		</circle>
		<line>
			<point x="-64" y="198" />
			<point x="-173" y="88" />
		</line>
		<infiniteline>
			<point x="-328" y="8" />
			<point x="-315" y="-8" />
		</infiniteline>
	</container>
	<container name="UmSegundoLayer" lineStyle="1" thickness="2">
		<color>
			<unsignedByte>102</unsignedByte>
			<unsignedByte>198</unsignedByte>
			<unsignedByte>193</unsignedByte>
		</color>
		<color>
			<unsignedByte>102</unsignedByte>
			<unsignedByte>198</unsignedByte>
			<unsignedByte>193</unsignedByte>
		</color>
		<arc>
			<point x="-278" y="43" />
			<point x="3" y="199" />
			<point x="-72" y="236" />
		</arc>
	</container>
	<container name="LayerDoAnderson" lineStyle="0" thickness="2.4">
		<color>
			<unsignedByte>207</unsignedByte>
			<unsignedByte>42</unsignedByte>
			<unsignedByte>148</unsignedByte>
		</color>
		<color>
			<unsignedByte>255</unsignedByte>
			<unsignedByte>0</unsignedByte>
			<unsignedByte>233</unsignedByte>
		</color>
		<polyline>
			<point x="-174" y="210" />
			<point x="-50" y="159" />
			<point x="-174" y="64" />
			<point x="4" y="62" />
			<point x="-170" y="8" />
		</polyline>
	</container>
	<container name="Layer 3" lineStyle="1" thickness="1">
		<color>
			<unsignedByte>255</unsignedByte>
			<unsignedByte>255</unsignedByte>
			<unsignedByte>255</unsignedByte>
		</color>
		<color>
			<unsignedByte>0</unsignedByte>
			<unsignedByte>0</unsignedByte>
			<unsignedByte>0</unsignedByte>
		</color>
		<arc>
			<point x="143" y="146" />
			<point x="41" y="-135" />
			<point x="268" y="-44" />
		</arc>
		<line>
			<point x="164" y="8" />
			<point x="-83" y="127" />
		</line>
	</container>
	<container name="LayerdoFabricio" lineStyle="0" thickness="1">
		<color>
			<unsignedByte>235</unsignedByte>
			<unsignedByte>24</unsignedByte>
			<unsignedByte>24</unsignedByte>
		</color>
		<color>
			<unsignedByte>0</unsignedByte>
			<unsignedByte>0</unsignedByte>
			<unsignedByte>0</unsignedByte>
		</color>
		<text>
			<point x="143.403" y="209.828" />
			<size>63.828</size>
			<content>Archimedes</content>
			<vector>
				<point x="1" y="0" />
			</vector>
		</text>
		<infiniteline>
			<point x="268" y="-44" />
			<point x="267.002" y="-44.063" />
		</infiniteline>
		<line>
			<point x="-1083.033" y="453.48" />
			<point x="957.756" y="-355.968" />
		</line>
	</container>
</drawing>

=== amage/Archimedes/plugins/br.org.archimedes.io.xml/InvalidExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<drawing xmlns="http://www.tarantulus.com/archimedes/FileXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tarantulus.com/archimedes/FileXMLSchema FileXMLSchema.xsd ">
<zoom>0.25418658283290013</zoom>
<viewport><point x="-142.85173245210717" y="-11.837661945181253" />
</viewport>
<container>
<line>
<point x="-395.0" y="-42.0" />
<point x="136.0" y="212.0" />
</line>
<line>
<point x="173.0" y="-117.0" />
<point x="-291.0" y="172.0" />
</line>
<infiniteLine>
<point x="-228.0" y="-199.0" />
<point x="40.0" y="29.0" />
</infiniteLine>
<circle>
<point x="-53.0" y="-183.0" />
<radius>269.1189328159578</radius>
</circle>
<semiLine>
<point x="-200.88158043235143" y="63.14569033621636" />
<point x="-606.7631608647029" y="249.29138067243275" />
</semiLine>
<arc>
<point x="-152.0" y="-96.0" />
<point x="-244.0" y="53.0" />
<point x="88.0" y="184.0" />
</arc>
<polyLine>
<point x="-182.0" y="-184.0" />
<point x="-513.0" y="56.0" />
<point x="62.0" y="157.0" />
<point x="220.0" y="-143.0" />
<point x="56.0" y="-211.0" />
<point x="395.0" y="-86.0" />
</polyLine>
<line>
<point x="-395.0" y="-42.0" />
<point x="136.0" y="212.0" />
</line>
<line>
<point x="173.0" y="-117.0" />
<point x="-291.0" y="172.0" />
</line>
<infiniteLine>
<point x="-228.0" y="-199.0" />
<point x="40.0" y="29.0" />
</infiniteLine>
<circle>
<point x="-53.0" y="-183.0" />
<radius>269.1189328159578</radius>
</circle>
<semiLine>
<point x="-200.88158043235143" y="63.14569033621636" />
<point x="-606.7631608647029" y="249.29138067243275" />
</semiLine>
<arc>
<point x="-152.0" y="-96.0" />
<point x="-244.0" y="53.0" />
<point x="88.0" y="184.0" />
</arc>
<polyLine>
<point x="-182.0" y="-184.0" />
<point x="-513.0" y="56.0" />
<point x="62.0" y="157.0" />
<point x="220.0" y="-143.0" />
<point x="56.0" y="-211.0" />
<point x="395.0" y="-86.0" />
</polyLine>
<line>
<point x="-395.0" y="-42.0" />
<point x="136.0" y="212.0" />
</line>
<line>
<point x="173.0" y="-117.0" />
<point x="-291.0" y="172.0" />
</line>
<infiniteLine>
<point x="-228.0" y="-199.0" />
<point x="40.0" y="29.0" />
</infiniteLine>
<circle>
<point x="-53.0" y="-183.0" />
<radius>269.1189328159578</radius>
</circle>
<semiLine>
<point x="-200.88158043235143" y="63.14569033621636" />
<point x="-606.7631608647029" y="249.29138067243275" />
</semiLine>
<arc>
<point x="-152.0" y="-96.0" />
<point x="-244.0" y="53.0" />
<point x="88.0" y="184.0" />
</arc>
<polyLine>
<point x="-182.0" y="-184.0" />
<point x="-513.0" y="56.0" />
<point x="62.0" y="157.0" />
<point x="220.0" y="-143.0" />
<point x="56.0" y="-211.0" />
<point x="395.0" y="-86.0" />
</polyLine>
<line>
<point x="-395.0" y="-42.0" />
<point x="136.0" y="212.0" />
</line>
<line>
<point x="173.0" y="-117.0" />
<point x="-291.0" y="172.0" />
</line>
<infiniteLine>
<point x="-228.0" y="-199.0" />
<point x="40.0" y="29.0" />
</infiniteLine>
<circle>
<point x="-53.0" y="-183.0" />
<radius>269.1189328159578</radius>
</circle>
<semiLine>
<point x="-200.88158043235143" y="63.14569033621636" />
<point x="-606.7631608647029" y="249.29138067243275" />
</semiLine>
<arc>
<point x="-152.0" y="-96.0" />
<point x="-244.0" y="53.0" />
<point x="88.0" y="184.0" />
</arc>
<polyLine>
<point x="-182.0" y="-184.0" />
<point x="-513.0" y="56.0" />
<point x="62.0" y="157.0" />
<point x="220.0" y="-143.0" />
<point x="56.0" y="-211.0" />
<point x="395.0" y="-86.0" />
</polyLine>
<line>
<point x="-395.0" y="-42.0" />
<point x="136.0" y="212.0" />
</line>
<line>
<point x="173.0" y="-117.0" />
<point x="-291.0" y="172.0" />
</line>
<infiniteLine>
<point x="-228.0" y="-199.0" />
<point x="40.0" y="29.0" />
</infiniteLine>
<circle>
<point x="-53.0" y="-183.0" />
<radius>269.1189328159578</radius>
</circle>
<semiLine>
<point x="-200.88158043235143" y="63.14569033621636" />
<point x="-606.7631608647029" y="249.29138067243275" />
</semiLine>
<arc>
<point x="-152.0" y="-96.0" />
<point x="-244.0" y="53.0" />
<point x="88.0" y="184.0" />
</arc>
<polyLine>
<point x="-182.0" y="-184.0" />
<point x="-513.0" y="56.0" />
<point x="62.0" y="157.0" />
<point x="220.0" y="-143.0" />
<point x="56.0" y="-211.0" />
<point x="395.0" y="-86.0" />
</polyLine>
<line>
<point x="-395.0" y="-42.0" />
<point x="136.0" y="212.0" />
</line>
<line>
<point x="173.0" y="-117.0" />
<point x="-291.0" y="172.0" />
</line>
<infiniteLine>
<point x="-228.0" y="-199.0" />
<point x="40.0" y="29.0" />
</infiniteLine>
<circle>
<point x="-53.0" y="-183.0" />
<radius>269.1189328159578</radius>
</circle>
<semiLine>
<point x="-200.88158043235143" y="63.14569033621636" />
<point x="-606.7631608647029" y="249.29138067243275" />
</semiLine>
<arc>
<point x="-152.0" y="-96.0" />
<point x="-244.0" y="53.0" />
<point x="88.0" y="184.0" />
</arc>
<polyLine>
<point x="-182.0" y="-184.0" />
<point x="-513.0" y="56.0" />
<point x="62.0" y="157.0" />
<point x="220.0" y="-143.0" />
<point x="56.0" y="-211.0" />
<point x="395.0" y="-86.0" />
</polyLine>
<line>
<point x="-395.0" y="-42.0" />
<point x="136.0" y="212.0" />
</line>
<line>
<point x="173.0" y="-117.0" />
<point x="-291.0" y="172.0" />
</line>
<infiniteLine>
<point x="-228.0" y="-199.0" />
<point x="40.0" y="29.0" />
</infiniteLine>
<circle>
<point x="-53.0" y="-183.0" />
<radius>269.1189328159578</radius>
</circle>
<semiLine>
<point x="-200.88158043235143" y="63.14569033621636" />
<point x="-606.7631608647029" y="249.29138067243275" />
</semiLine>
<arc>
<point x="-152.0" y="-96.0" />
</arc>
<polyLine>
<point x="-182.0" y="-184.0" />
<point x="-513.0" y="56.0" />
<point x="62.0" y="157.0" />
<point x="220.0" y="-143.0" />
<point x="56.0" y="-211.0" />
<point x="395.0" y="-86.0" />
</polyLine>
</container>
</drawing>
